# Generated by Django 5.2.9 on 2025-12-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_galleryimage_options_alter_galleryimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='caption',
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
